package com.doseleaf.app;
import android.content.*;
import android.database.*;
import android.database.sqlite.*;
import org.json.*;
import java.io.*;
import java.time.*;
import java.util.*;

public class Database extends SQLiteOpenHelper {
 public Database(Context c){super(c,"doseleaf.db",null,1);}
 public void onCreate(SQLiteDatabase db){db.execSQL("CREATE TABLE prescriptions(id TEXT PRIMARY KEY,date TEXT NOT NULL,data TEXT NOT NULL,photo TEXT)");db.execSQL("CREATE TABLE doses(key TEXT PRIMARY KEY,status TEXT NOT NULL)");}
 public void onUpgrade(SQLiteDatabase db,int old,int next){throw new IllegalStateException("Unsupported migration");}
 public JSONArray list() throws Exception {JSONArray a=new JSONArray();try(Cursor c=getReadableDatabase().rawQuery("SELECT data,photo FROM prescriptions ORDER BY date DESC,rowid DESC",null)){while(c.moveToNext()){JSONObject p=new JSONObject(c.getString(0));p.put("photo",!c.isNull(1));a.put(p);}}return a;}
 public JSONObject logs(String date)throws Exception{LocalDate.parse(date);JSONObject j=new JSONObject();try(Cursor c=getReadableDatabase().rawQuery("SELECT key,status FROM doses WHERE key LIKE ?",new String[]{date+"|%"})){while(c.moveToNext())j.put(c.getString(0),c.getString(1));}return j;}
 public void mark(String key,String status)throws Exception{if(!status.equals("taken")&&!status.equals("pending"))throw new Exception("Invalid status");String[] parts=key.split("\\|");if(parts.length!=4)throw new Exception("Invalid dose");LocalDate date=LocalDate.parse(parts[0]);JSONObject p=find(parts[1]);if(p==null)throw new Exception("Prescription not found");boolean found=false;JSONArray ms=p.getJSONArray("medicines");for(int i=0;i<ms.length();i++){JSONObject m=ms.getJSONObject(i);if(!m.getString("id").equals(parts[2])||m.optBoolean("unscheduled"))continue;LocalDate start=LocalDate.parse(m.getString("start")),end=LocalDate.parse(m.getString("end"));if(date.isBefore(start)||date.isAfter(end))continue;JSONArray times=m.getJSONArray("times");for(int n=0;n<times.length();n++)if(times.getString(n).equals(parts[3]))found=true;}if(!found)throw new Exception("Dose not found");ContentValues v=new ContentValues();v.put("key",key);v.put("status",status);getWritableDatabase().insertWithOnConflict("doses",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
 public JSONObject find(String id)throws Exception{try(Cursor c=getReadableDatabase().rawQuery("SELECT data FROM prescriptions WHERE id=?",new String[]{id})){return c.moveToFirst()?new JSONObject(c.getString(0)):null;}}
 public String photo(String id){try(Cursor c=getReadableDatabase().rawQuery("SELECT photo FROM prescriptions WHERE id=?",new String[]{id})){return c.moveToFirst()?c.getString(0):null;}}
 public void save(JSONObject p,String photo)throws Exception{validate(p);if(find(p.getString("id"))!=null)return;ContentValues v=new ContentValues();v.put("id",p.getString("id"));v.put("date",p.getString("date"));v.put("data",p.toString());v.put("photo",photo);getWritableDatabase().insertOrThrow("prescriptions",null,v);}
 public static void validate(JSONObject p)throws Exception{UUID.fromString(p.getString("id"));LocalDate.parse(p.getString("date"));if(!p.optBoolean("confirmed"))throw new Exception("Review and confirm this prescription first");JSONArray qs=p.optJSONArray("clarifications");if(qs!=null)for(int q=0;q<qs.length();q++)if(qs.getJSONObject(q).optString("answer").trim().isEmpty())throw new Exception("Resolve every clarification first");JSONArray ms=p.getJSONArray("medicines");if(ms.length()<1||ms.length()>20)throw new Exception("Add between 1 and 20 medicines");for(int i=0;i<ms.length();i++){JSONObject m=ms.getJSONObject(i);UUID.fromString(m.getString("id"));if(m.optString("name").trim().isEmpty()||m.optString("dose").trim().isEmpty())throw new Exception("Confirm each medicine and dose");LocalDate start=LocalDate.parse(m.getString("start")),end=LocalDate.parse(m.getString("end"));if(end.isBefore(start))throw new Exception("End date is before start date");JSONArray times=m.getJSONArray("times");if(!m.optBoolean("unscheduled")&&times.length()==0)throw new Exception("Add a reminder time or choose no daily reminders");HashSet<String> unique=new HashSet<>();for(int t=0;t<times.length();t++){String time=times.getString(t);if(!time.matches("([01]\\d|2[0-3]):[0-5]\\d")||!unique.add(time))throw new Exception("Check reminder times");}}}
}
