package com.doseleaf.app;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.media.ExifInterface;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.util.Base64;import android.view.*;import android.webkit.*;import android.widget.Toast;import org.json.*;import java.io.*;import java.net.*;import javax.net.ssl.HttpsURLConnection;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;
public class MainActivity extends Activity {
 private WebView web;private final ExecutorService worker=Executors.newSingleThreadExecutor();private static final int PHOTO=100,CAMERA=101,NOTIFY=102;
 @Override public void onCreate(Bundle saved){super.onCreate(saved);web=new WebView(this);setContentView(web);web.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(i.getSystemWindowInsetLeft(),i.getSystemWindowInsetTop(),i.getSystemWindowInsetRight(),i.getSystemWindowInsetBottom());return i;});web.requestApplyInsets();WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(false);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setSupportMultipleWindows(false);s.setJavaScriptCanOpenWindowsAutomatically(false);WebView.setWebContentsDebuggingEnabled(false);web.addJavascriptInterface(new Bridge(),"Doseleaf");web.setWebChromeClient(new WebChromeClient());web.setWebViewClient(new WebViewClient(){
 public WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest r){Uri u=r.getUrl();try{if(!"https".equals(u.getScheme())||!"doseleaf.local".equals(u.getHost()))return blocked();String path=u.getPath();if(path==null||path.contains(".."))return blocked();if(path.startsWith("/photo/")){String id=path.substring(7);UUID.fromString(id);try(Database db=new Database(MainActivity.this)){String filename=db.photo(id);if(filename==null)return blocked();String type=filename.endsWith(".png")?"image/png":filename.endsWith(".webp")?"image/webp":"image/jpeg";return new WebResourceResponse(type,null,new FileInputStream(new File(getFilesDir(),filename)));}}String asset=path.equals("/")?"index.html":path.substring(1);String mime=asset.endsWith(".js")?"text/javascript":asset.endsWith(".css")?"text/css":asset.endsWith(".svg")?"image/svg+xml":"text/html";return new WebResourceResponse(mime,"UTF-8",getAssets().open(asset));}catch(Exception e){return blocked();}}
 public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();if("doseleaf.local".equals(u.getHost()))return !"https".equals(u.getScheme());if("https".equals(u.getScheme())&&("aistudio.google.com".equals(u.getHost())||"ai.google.dev".equals(u.getHost()))){try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception ignored){}}return true;}
 });web.loadUrl("https://doseleaf.local/");Scheduler.channel(this);worker.execute(()->Scheduler.all(this));}
 private WebResourceResponse blocked(){return new WebResourceResponse("text/plain","UTF-8",403,"Forbidden",Collections.emptyMap(),new ByteArrayInputStream(new byte[0]));}
 private void result(String id,JSONObject j){runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())web.evaluateJavascript("window.doseleafResult("+JSONObject.quote(id)+","+j+")",null);});}
 private JSONObject error(String text){JSONObject j=new JSONObject();try{j.put("error",text);}catch(Exception ignored){}return j;}
 private void photoEvent(JSONObject j){runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())web.evaluateJavascript("window.dispatchEvent(new CustomEvent('doseleaf-photo',{detail:"+j+"}))",null);});}
 public final class Bridge {
 @JavascriptInterface public void pickPhoto(boolean camera){runOnUiThread(()->{try{if(camera){File f=new File(getCacheDir(),"camera.jpg");if(f.exists())f.delete();Uri uri=Uri.parse("content://com.doseleaf.app.files/camera.jpg");Intent i=new Intent("android.media.action.IMAGE_CAPTURE");i.putExtra("output",uri);i.setClipData(ClipData.newRawUri("Prescription photo",uri));i.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivityForResult(i,CAMERA);}else startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),PHOTO);}catch(Exception e){photoEvent(error(camera?"Could not open a camera app on this device.":"Could not open the photo picker."));}});}
 @JavascriptInterface public void request(String action,String payload,String id){if(payload==null||payload.length()>13*1024*1024){result(id,error("The image is too large. Use a smaller photo."));return;}worker.execute(()->{try{JSONObject p=new JSONObject(payload),out=new JSONObject();try(Database db=new Database(MainActivity.this)){switch(action){
 case "list":out.put("records",db.list());break;
 case "logs":out.put("logs",db.logs(p.getString("date")));break;
 case "mark":db.mark(p.getString("key"),p.getString("status"));out.put("ok",true);break;
 case "save":{JSONObject record=p.getJSONObject("record");Database.validate(record);String rid=record.getString("id"),filename=null;if(db.find(rid)==null&&!p.isNull("photo")){byte[] bytes=Base64.decode(p.getString("photo"),Base64.DEFAULT);if(bytes.length>8*1024*1024)throw new Exception("Photo must be under 8 MB");String mime=p.optString("mime");filename=rid+("image/png".equals(mime)?".png":"image/webp".equals(mime)?".webp":".jpg");try(FileOutputStream f=new FileOutputStream(new File(getFilesDir(),filename))){f.write(bytes);}}db.save(record,filename);Scheduler.one(MainActivity.this,record);out.put("ok",true);break;}
 case "extract":out.put("extraction",extract(p));break;
 case "reminders":runOnUiThread(()->notificationSettings());out.put("ok",true);break;
 case "export":{File f=new File(getCacheDir(),"reminders.ics");try(FileOutputStream stream=new FileOutputStream(f)){stream.write(p.getString("content").getBytes(StandardCharsets.UTF_8));}runOnUiThread(()->{try{Intent share=new Intent(Intent.ACTION_SEND).setType("text/calendar").putExtra(Intent.EXTRA_STREAM,Uri.parse("content://com.doseleaf.app.files/reminders.ics")).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(share,"Export medicine reminders"));}catch(Exception e){Toast.makeText(MainActivity.this,"No compatible calendar or file app is installed",Toast.LENGTH_LONG).show();}});out.put("ok",true);break;}
 default:throw new Exception("Unsupported request");}}result(id,out);
 }catch(SocketTimeoutException e){result(id,error("Gemini timed out. Retry with a clearer or smaller photo."));}catch(Exception e){result(id,error(e.getMessage()==null?"Could not complete this action.":e.getMessage()));}});}
 }
 private JSONObject extract(JSONObject p)throws Exception{
 String key=p.optString("apiKey"),model=p.optString("model","gemini-3.8-flash"),mime=p.optString("mime"),photo=p.optString("photo");if(key.isEmpty())throw new Exception("Connect a Gemini API key first.");if(!model.matches("[a-zA-Z0-9._-]{1,100}"))throw new Exception("Invalid Gemini model ID.");if(!Arrays.asList("image/jpeg","image/png","image/webp").contains(mime)||photo.length()>12*1024*1024)throw new Exception("Use a JPG, PNG or WebP image under 8 MB.");String prompt=new String(readAll(getAssets().open("prescription-extraction.txt"),50000),StandardCharsets.UTF_8);JSONObject schema=new JSONObject(new String(readAll(getAssets().open("extraction-schema.json"),50000),StandardCharsets.UTF_8));
 JSONObject image=new JSONObject().put("inlineData",new JSONObject().put("mimeType",mime).put("data",photo));JSONArray parts=new JSONArray().put(new JSONObject().put("text","Read this prescription and ask specific clarification questions for unclear instructions.")).put(image);JSONObject request=new JSONObject().put("systemInstruction",new JSONObject().put("parts",new JSONArray().put(new JSONObject().put("text",prompt)))).put("contents",new JSONArray().put(new JSONObject().put("role","user").put("parts",parts))).put("generationConfig",new JSONObject().put("responseMimeType","application/json").put("responseJsonSchema",schema).put("maxOutputTokens",12000));
 HttpsURLConnection conn=(HttpsURLConnection)new URL("https://generativelanguage.googleapis.com/v1beta/models/"+model+":generateContent").openConnection();conn.setConnectTimeout(20000);conn.setReadTimeout(90000);conn.setRequestMethod("POST");conn.setRequestProperty("Content-Type","application/json");conn.setRequestProperty("x-goog-api-key",key);conn.setDoOutput(true);try{try(OutputStream o=conn.getOutputStream()){o.write(request.toString().getBytes(StandardCharsets.UTF_8));}int status=conn.getResponseCode();if(status!=200)throw new Exception(status==429?"Gemini quota reached. Check your API plan or try later.":status==404?"Gemini model not found. Check the model ID.":status==400||status==403?"Gemini rejected the request. Check your API key and model access.":"Gemini is temporarily unavailable.");JSONObject response=new JSONObject(new String(readAll(conn.getInputStream(),2*1024*1024),StandardCharsets.UTF_8));JSONObject candidate=response.getJSONArray("candidates").getJSONObject(0);if(!"STOP".equals(candidate.optString("finishReason")))throw new Exception("Gemini did not finish reading. Try a clearer photo.");JSONArray outputParts=candidate.getJSONObject("content").getJSONArray("parts");StringBuilder text=new StringBuilder();for(int i=0;i<outputParts.length();i++){JSONObject part=outputParts.getJSONObject(i);if(!part.optBoolean("thought"))text.append(part.optString("text"));}JSONObject output=new JSONObject(text.toString());JSONArray meds=output.getJSONArray("medicines");if(meds.length()>20)throw new Exception("Upload one prescription page at a time.");output.getJSONArray("questions");for(int i=0;i<meds.length();i++){JSONObject m=meds.getJSONObject(i);for(String field:new String[]{"name","strength","dose","route","frequency","duration","food","source"})m.getString(field);m.getJSONArray("questions");JSONArray times=m.getJSONArray("times");for(int t=0;t<times.length();t++)if(!times.getString(t).matches("([01]\\d|2[0-3]):[0-5]\\d"))throw new Exception("Invalid time in reading. Please retry.");}return output;}finally{conn.disconnect();}}
 private void notificationSettings(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},NOTIFY);return;}NotificationManager nm=getSystemService(NotificationManager.class);if(!nm.areNotificationsEnabled()){startActivity(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()));return;}AlarmManager am=getSystemService(AlarmManager.class);if(Build.VERSION.SDK_INT>=31&&!am.canScheduleExactAlarms()){startActivity(new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM,Uri.parse("package:"+getPackageName())));return;}worker.execute(()->Scheduler.all(this));Toast.makeText(this,"Android reminders are enabled",Toast.LENGTH_LONG).show();}
 @Override public void onRequestPermissionsResult(int code,String[] ps,int[] grants){super.onRequestPermissionsResult(code,ps,grants);if(code==NOTIFY&&grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED)notificationSettings();else if(code==NOTIFY)Toast.makeText(this,"Notifications are off. Enable them in Android settings.",Toast.LENGTH_LONG).show();}
 @Override public void onResume(){super.onResume();worker.execute(()->Scheduler.all(this));}
 @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK)return;Uri uri=req==CAMERA?Uri.fromFile(new File(getCacheDir(),"camera.jpg")):req==PHOTO&&data!=null?data.getData():null;if(uri==null)return;worker.execute(()->{try{byte[] original=readAll(getContentResolver().openInputStream(uri),30*1024*1024);BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(original,0,original.length,bounds);if(bounds.outWidth<1||bounds.outHeight<1)throw new Exception("Could not read this image. Try JPG or PNG.");BitmapFactory.Options opts=new BitmapFactory.Options();int sample=1;while(Math.max(bounds.outWidth,bounds.outHeight)/sample>2600)sample*=2;opts.inSampleSize=sample;Bitmap bitmap=BitmapFactory.decodeByteArray(original,0,original.length,opts);if(bitmap==null)throw new Exception("Could not decode photo.");ExifInterface exif=new ExifInterface(new ByteArrayInputStream(original));int orientation=exif.getAttributeInt(ExifInterface.TAG_ORIENTATION,1);Matrix matrix=new Matrix();switch(orientation){case 2:matrix.setScale(-1,1);break;case 3:matrix.setRotate(180);break;case 4:matrix.setScale(1,-1);break;case 5:matrix.setRotate(90);matrix.postScale(-1,1);break;case 6:matrix.setRotate(90);break;case 7:matrix.setRotate(-90);matrix.postScale(-1,1);break;case 8:matrix.setRotate(-90);break;}Bitmap oriented=Bitmap.createBitmap(bitmap,0,0,bitmap.getWidth(),bitmap.getHeight(),matrix,true);ByteArrayOutputStream bytes=new ByteArrayOutputStream();oriented.compress(Bitmap.CompressFormat.JPEG,94,bytes);if(oriented!=bitmap)oriented.recycle();bitmap.recycle();if(bytes.size()>8*1024*1024)throw new Exception("Choose a smaller photo.");photoEvent(new JSONObject().put("name","prescription.jpg").put("mime","image/jpeg").put("base64",Base64.encodeToString(bytes.toByteArray(),Base64.NO_WRAP)));}catch(Exception e){photoEvent(error(e.getMessage()==null?"Could not read photo.":e.getMessage()));}finally{if(req==CAMERA)new File(getCacheDir(),"camera.jpg").delete();}});}
 static byte[] readAll(InputStream stream,int max)throws IOException{if(stream==null)throw new IOException("File unavailable");try(InputStream in=stream;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1){if(out.size()+n>max)throw new IOException("File too large");out.write(buf,0,n);}return out.toByteArray();}}
 @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
 @Override protected void onDestroy(){web.removeJavascriptInterface("Doseleaf");web.destroy();worker.shutdown();super.onDestroy();}
}
