package com.doseleaf.app;
import android.app.*;import android.content.*;import android.os.Build;import android.net.Uri;import org.json.*;import java.time.*;
public class Scheduler {
 public static final String CHANNEL="dose-reminders";
 public static void channel(Context c){NotificationManager n=c.getSystemService(NotificationManager.class);NotificationChannel ch=new NotificationChannel(CHANNEL,"Medicine reminders",NotificationManager.IMPORTANCE_HIGH);ch.setDescription("Reminders from your confirmed prescriptions");ch.setLockscreenVisibility(Notification.VISIBILITY_PRIVATE);n.createNotificationChannel(ch);}
 public static void all(Context c){try(Database db=new Database(c)){JSONArray ps=db.list();for(int i=0;i<ps.length();i++)one(c,ps.getJSONObject(i));}catch(Exception ignored){}}
 public static void one(Context c,JSONObject p)throws Exception{JSONArray ms=p.getJSONArray("medicines");for(int i=0;i<ms.length();i++){JSONObject m=ms.getJSONObject(i);if(m.optBoolean("unscheduled"))continue;JSONArray ts=m.getJSONArray("times");for(int n=0;n<ts.length();n++)next(c,p.getString("id"),m,ts.getString(n));}}
 public static void next(Context c,String pid,JSONObject m,String time)throws Exception{ZonedDateTime now=ZonedDateTime.now();LocalDate start=LocalDate.parse(m.getString("start")),end=LocalDate.parse(m.getString("end"));LocalDate day=now.toLocalDate().isBefore(start)?start:now.toLocalDate();ZonedDateTime due=ZonedDateTime.of(day,LocalTime.parse(time),ZoneId.systemDefault());if(!due.isAfter(now))due=due.plusDays(1);if(due.toLocalDate().isAfter(end))return;String identity=pid+"|"+m.getString("id")+"|"+time;Intent intent=new Intent(c,ReminderReceiver.class).setData(Uri.parse("doseleaf://reminder/"+Uri.encode(identity))).putExtra("pid",pid).putExtra("mid",m.getString("id")).putExtra("time",time).putExtra("date",due.toLocalDate().toString());PendingIntent pending=PendingIntent.getBroadcast(c,0,intent,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);AlarmManager am=c.getSystemService(AlarmManager.class);long at=due.toInstant().toEpochMilli();if(Build.VERSION.SDK_INT<31||am.canScheduleExactAlarms())am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pending);else am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pending);}
}
