import type {Prescription} from './lib/model';
declare global{interface Window{Doseleaf?:{request:(action:string,payload:string,id:string)=>void;pickPhoto:(camera:boolean)=>void};doseleafResult?:(id:string,result:{error?:string;[key:string]:unknown})=>void}}
const pending=new Map<string,{resolve:(value:any)=>void;reject:(reason:Error)=>void;timer:ReturnType<typeof setTimeout>}>();
window.doseleafResult=(id,result)=>{const p=pending.get(id);if(!p)return;clearTimeout(p.timer);pending.delete(id);if(result.error)p.reject(new Error(result.error));else p.resolve(result);};
function call<T=any>(action:string,payload:unknown={}):Promise<T>{return new Promise((resolve,reject)=>{if(!window.Doseleaf){reject(new Error('Open the installed Android app to use this feature.'));return}const id=crypto.randomUUID();const timer=setTimeout(()=>{pending.delete(id);reject(new Error('Request timed out. Please try again.'))},110000);pending.set(id,{resolve,reject,timer});window.Doseleaf.request(action,JSON.stringify(payload),id);});}
async function imageBase64(file:File){const buf=new Uint8Array(await file.arrayBuffer());let text='';for(let i=0;i<buf.length;i+=8192)text+=String.fromCharCode(...buf.subarray(i,i+8192));return btoa(text);}
export async function nativeApi<T={ok:boolean}>(path:string,init?:RequestInit):Promise<T>{if(path==='/api/prescriptions'&&!init)return call<T>('list');if(path.startsWith('/api/doses?'))return call<T>('logs',{date:path.split('=')[1]});if(path==='/api/doses')return call<T>('mark',JSON.parse(String(init?.body)));if(path==='/api/extract'&&!init)return {configured:false,model:'gemini-3.8-flash'} as T;if(path==='/api/extract'){const f=init!.body as FormData;const file=f.get('photo') as File;return call<T>('extract',{photo:await imageBase64(file),mime:file.type,apiKey:f.get('apiKey'),model:f.get('model')})}if(path==='/api/prescriptions'){const f=init!.body as FormData;const file=f.get('photo') as File|null;return call<T>('save',{record:JSON.parse(String(f.get('data'))),photo:file?await imageBase64(file):null,mime:file?.type||null})}throw new Error('Unsupported operation');}
export function pickPhoto(camera:boolean){window.Doseleaf?.pickPhoto(camera);}
export function reminderSettings(){return call('reminders');}
export function exportNativeCalendar(content:string){return call('export',{content});}
