import { z } from 'zod';
export const dateSchema=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>{const d=new Date(s+'T12:00:00Z');return !isNaN(d.getTime())&&d.toISOString().slice(0,10)===s;},'Invalid date');
export const medicineSchema=z.object({id:z.string().uuid(),name:z.string().trim().min(1).max(150),dose:z.string().trim().min(1).max(150),instructions:z.string().trim().max(2000),strength:z.string().max(150).default(''),frequency:z.string().max(500).default(''),duration:z.string().max(500).default(''),source:z.string().max(3000).default(''),unscheduled:z.boolean().default(false),times:z.array(z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/)).max(8).refine(t=>new Set(t).size===t.length),start:dateSchema,end:dateSchema}).refine(m=>m.end>=m.start&&(m.unscheduled||m.times.length>0),'Check dates and reminder times');
export const prescriptionSchema=z.object({id:z.string().uuid(),title:z.string().trim().min(1).max(150),doctor:z.string().trim().max(150),date:dateSchema,medicines:z.array(medicineSchema).min(1).max(20),confirmed:z.literal(true),clarifications:z.array(z.object({question:z.string().max(3000),answer:z.string().trim().min(1).max(3000)})).max(100).default([])});
export type Medicine=z.infer<typeof medicineSchema>;
export type Prescription=z.infer<typeof prescriptionSchema>&{photo?:boolean};
export function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function candidates(raw:string){return raw.split('\n').map(s=>s.trim()).filter(s=>/\b\d+(?:\.\d+)?\s*(?:mg|mcg|ml|iu|g)\b/i.test(s)).slice(0,20).map(s=>({id:crypto.randomUUID(),name:s.slice(0,150),dose:'',instructions:'',times:[],start:localDate(),end:localDate()}));}
export function calendarText(records:Prescription[]){const esc=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const stamp=new Date().toISOString().replace(/[-:]/g,'').split('.')[0]+'Z';const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Doseleaf//Medicine reminders//EN','CALSCALE:GREGORIAN'];for(const p of records)for(const m of p.medicines)for(const t of m.times){const start=m.start.replace(/-/g,'')+'T'+t.replace(':','')+'00';const days=Math.round((Date.parse(m.end)-Date.parse(m.start))/86400000)+1;lines.push('BEGIN:VEVENT',`UID:${p.id}-${m.id}-${t.replace(':','')}@doseleaf`,`DTSTAMP:${stamp}`,`DTSTART:${start}`,'DURATION:PT5M',`RRULE:FREQ=DAILY;COUNT=${days}`,`SUMMARY:${esc(m.name+' — '+m.dose)}`,`DESCRIPTION:${esc(m.instructions+'\nFollow only your confirmed prescription. Local device time.')}`,'BEGIN:VALARM','TRIGGER:PT0M','ACTION:DISPLAY',`DESCRIPTION:${esc(m.name+' — '+m.dose)}`,'END:VALARM','END:VEVENT');}lines.push('END:VCALENDAR');return lines.map(line=>{let out='',count=0;for(const c of line){const bytes=new TextEncoder().encode(c).length;if(count+bytes>73){out+='\r\n ';count=1;}out+=c;count+=bytes;}return out;}).join('\r\n')+'\r\n';}
